### PR TITLE
fixing ansible-test sanity issues. 

### PR DESCRIPTION
**Pull request by ar-india**
sanity test log as below

ansible-test sanity  > ansible_nimble_modules_sanity.log 2>&1

Running sanity test 'action-plugin-docs' with Python 3.6
Running sanity test 'ansible-doc' with Python 3.6
Running sanity test 'changelog' with Python 3.6
WARNING: Skipping sanity test 'compile' on Python 2.6 due to missing interpreter.
WARNING: Skipping sanity test 'compile' on Python 2.7 due to missing interpreter.
WARNING: Skipping sanity test 'compile' on Python 3.5 due to missing interpreter.
Running sanity test 'compile' with Python 3.6
WARNING: Skipping sanity test 'compile' on Python 3.7 due to missing interpreter.
Running sanity test 'compile' with Python 3.8
WARNING: Skipping sanity test 'compile' on Python 3.9 due to missing interpreter.
Running sanity test 'empty-init' with Python 3.6
Running sanity test 'future-import-boilerplate' with Python 3.6
Running sanity test 'ignores'
WARNING: Skipping sanity test 'import' on Python 2.6 due to missing interpreter.
WARNING: Skipping sanity test 'import' on Python 2.7 due to missing interpreter.
WARNING: Skipping sanity test 'import' on Python 3.5 due to missing interpreter.
Running sanity test 'import' with Python 3.6
WARNING: Skipping sanity test 'import' on Python 3.7 due to missing interpreter.
Running sanity test 'import' with Python 3.8
WARNING: Skipping sanity test 'import' on Python 3.9 due to missing interpreter.
Running sanity test 'line-endings' with Python 3.6
Running sanity test 'metaclass-boilerplate' with Python 3.6
Running sanity test 'no-assert' with Python 3.6
Running sanity test 'no-basestring' with Python 3.6
Running sanity test 'no-dict-iteritems' with Python 3.6
Running sanity test 'no-dict-iterkeys' with Python 3.6
Running sanity test 'no-dict-itervalues' with Python 3.6
Running sanity test 'no-get-exception' with Python 3.6
Running sanity test 'no-illegal-filenames' with Python 3.6
Running sanity test 'no-main-display' with Python 3.6
Running sanity test 'no-smart-quotes' with Python 3.6
Running sanity test 'no-unicode-literals' with Python 3.6
Running sanity test 'pep8' with Python 3.6
Running sanity test 'pslint'
Running sanity test 'pylint' with Python 3.6
Running sanity test 'replace-urlopen' with Python 3.6
Running sanity test 'rstcheck' with Python 3.6
Running sanity test 'runtime-metadata' with Python 3.6
Running sanity test 'shebang' with Python 3.6
Running sanity test 'shellcheck'
Running sanity test 'symlinks' with Python 3.6
Running sanity test 'use-argspec-type-path' with Python 3.6
Running sanity test 'use-compat-six' with Python 3.6
Running sanity test 'validate-modules' with Python 3.6
Running sanity test 'yamllint' with Python 3.6
WARNING: Skipping sanity test 'yamllint' due to missing libyaml support in PyYAML.
WARNING: Reviewing previous 11 warning(s):
WARNING: Skipping sanity test 'compile' on Python 2.6 due to missing interpreter.
WARNING: Skipping sanity test 'compile' on Python 2.7 due to missing interpreter.
WARNING: Skipping sanity test 'compile' on Python 3.5 due to missing interpreter.
WARNING: Skipping sanity test 'compile' on Python 3.7 due to missing interpreter.
WARNING: Skipping sanity test 'compile' on Python 3.9 due to missing interpreter.
WARNING: Skipping sanity test 'import' on Python 2.6 due to missing interpreter.
WARNING: Skipping sanity test 'import' on Python 2.7 due to missing interpreter.
WARNING: Skipping sanity test 'import' on Python 3.5 due to missing interpreter.
WARNING: Skipping sanity test 'import' on Python 3.7 due to missing interpreter.
WARNING: Skipping sanity test 'import' on Python 3.9 due to missing interpreter.
WARNING: Skipping sanity test 'yamllint' due to missing libyaml support in PyYAML.

### CODE REVIEW

**Comment by ar-india** [comment]
have fixed the sanity test issues.

**Comment by datamattsson** [comment]
Can you run the sanity checks on our modules in the collection only?

**Comment by ar-india** [comment]
@datamattsson 
that is what i already did

(venv) [root@centos80x64tmp nimble]# pwd
/root/.ansible/collections/ansible_collections/hpe/nimble

**Review by rgcostea — APPROVED** [review]
lgtm

**Pull request merged**
